### PR TITLE
Update lharc.c

### PR DESCRIPTION
**Pull request by dude789**

### CODE REVIEW

**Comment by jca02266** [comment]
Why did you remove the configured option?

**Comment by dude789** [comment]
Sorry. It was empty at me and i didn't find it in the source code. I see now its definet in the ./configure file. I add it again.

**Comment by jca02266** [comment]
> if (LHA_CONFIGURE_OPTIONS != "")

I think you should use strcmp() or strlen() == 0.

**Comment by jca02266** [comment]
Thank you for your contribution!
Your changes have been merged.

**Pull request merged**
